### ISSUE TITLE
compile config to a module instead of keeping it in a map

### ISSUE THREAD

**Issue by ghost** [xaptum/oneup_metrics#6]
Hi! Really liked the talk.

So, can maybe the configuration be compiled to a module like in https://github.com/discordapp/fastglobal or https://github.com/lpgauth/foil?

**Comment by iguberman** [comment]
@asd1o2487c Thanks so much for this great suggestion!  I will look into this for sure.   Was already looking at https://github.com/mrallen1/fling which I beleive is a similar idea per @mrallen1 suggestion at the conference.  You guys are fantastic audience! :)

**Comment by jadeallenx** [comment]
Yup that's what I suggested :)  I didn't know about those other libraries though! Neat.

**Comment by iguberman** [comment]
As it turns out fling/foil currently don't support refs (so we can't store oneup counter refs in foil or fling).   The problem is not that they can't store them -- functionally there is a way around it, but performance is comparable to `ets:lookup` with read concurrency, so ultimately there is no point of doing it that way.  See discussion thread here: https://github.com/lpgauth/foil/pull/3
